target:
  url: "https://www.itjobs.pt/emprego?q=DevOps&location="
  data:
    list:
      container: ".block.borderless"
      fields:
        - name: "job_title"
          selector: ".title"
          type: "text"

        - name: "day"
          selector: ".d-d"
          type: "number"

        - name: "month"
          selector: ".d-m"
          type: "text"

        - name: "image"
          selector: ".img-container"
          type: "image"

        - name: "company"
          selector: ".list-name"
          type: "text"

        - name: "location"
          selector: ".fa-map-marker"
          type: "text"
          position: "next"

        - name: "salary"
          when: ".fa-coins"
          selector: ".fa-coins"
          type: "text"
          position: "next"
          transform:
            - operation: "splice"
              splice_index: 1
  pagination:
    selector: ".last"
    max_pages: 5
    navigation: "button"
output:
  format: "json"
  file: "itjobs-devops.json"
